
name: Deploy on Tag

on:
  push:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    
     - name: Checkout code
       uses: actions/checkout@v2
    
     - name: Setting environment variables..
       run: |
        echo "AWS_DEFAULT_REGION=ap-south-1" >> $GITHUB_ENV
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
        echo "AWS_INSTANCE_ID=${{ secrets.AWS_INSTANCE_ID }}" >> $GITHUB_ENV
        echo "AWS_IAM_ARN=${{ secrets.AWS_IAM_ARN }}" >> $GITHUB_ENV
        echo "AWS_TAG=${{ secrets.AWS_TAG }}" >> $GITHUB_ENV
        echo "AWS_TAG_VALUE=code-deploy" >> $GITHUB_ENV
        
     - name: Retrieve tag value
       run: |
        echo '#!/bin/bash' > tag_value.sh
        echo 'TAG_VALUE=$(aws ec2 describe-instances --instance-ids $AWS_INSTANCE_ID --query "Reservations[].Instances[].Tags[?Key==`'$AWS_TAG'`].Value" --output text)' >> tag_value.sh
        echo 'echo "$TAG_VALUE" == "$AWS_TAG_VALUE"' >> tag_value.sh
        echo 'if [ "$TAG_VALUE" == "$AWS_TAG_VALUE" ]; then' >> tag_value.sh
        echo '  cd /opt/laravel && touch sample.txt' >> tag_value.sh
        echo 'else' >> tag_value.sh
        echo '  echo "Tag value mismatch"' >> tag_value.sh
        echo 'fi' >> tag_value.sh
        chmod +x tag_value.sh
        ./tag_value.sh


       
     
       
        
     
              
          

     
          
     
