
name: Deploy on Tag

on:
  push:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    
     - name: Checkout code
       uses: actions/checkout@v2
    
     - name: Setting environment variables..
       run: |
        echo "AWS_DEFAULT_REGION=ap-south-1" >> $GITHUB_ENV
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
        echo "AWS_INSTANCE_ID=${{ secrets.AWS_INSTANCE_ID }}" >> $GITHUB_ENV
        echo "AWS_IAM_ARN=${{ secrets.AWS_IAM_ARN }}" >> $GITHUB_ENV
        echo "AWS_TAG_VALUE=${{ secrets.AWS_TAG_VALUE }}" >> $GITHUB_ENV
        echo "AWS_TAG=${{ secrets.AWS_TAG }}" >> $GITHUB_ENV
        
     - name: Retrieve tag value
       id: extract_tag
       run: echo "TAG=${GITHUB_REF/refs\/tags\//}"
       
     - name: Check server tag
       run: |
          if [[ ${{ github.ref }} == 'refs/tags/$AWS_TAG_VALUE' ]]; then
            echo "::set-output name=deploy::true"
          else
            echo "::set-output name=deploy::false"
          fi
          id: check_tag

     - name: Deploy to server
       if: steps.check_tag.outputs.deploy == 'true'
       run: |
        cd /opt/laravel/ && touch demo.txt
       
     

     
          
     
